var cards = [
    {'filename':'cleistothecium.png',     'question':'Ascocarp type?',      'answer':'cleistothecium',                'attrcolor':'black', 'attribution':'<a href="https://commons.wikimedia.org/wiki/File:Uncinula_%28Oidium%29_cleistothecium_40X_%281%29.png">Image from Wikipedia</a>'},
    {'filename':'ascus.jpg',              'question':'Botanical term?',     'answer':'asci bearing ascospores',       'attrcolor':'white', 'attribution':'<a href="https://en.wikipedia.org/wiki/Ascus#/media/File:Morelasci.jpg">Image from Wikipedia</a>'},
    {'filename':'basidia.jpg',            'question':'Botanical term?',     'answer':'basidia bearing basidiospores', 'attrcolor':'white', 'attribution':'<a href="https://thebiologyprimer.com/the-origin-and-evolution-of-fungi">Image from The Biology Primer</a>'},
    {'filename':'slimemold.jpg',          'question':'Type of organism?',   'answer':'slime mold',                    'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis'},
    {'filename':'basidiocarp.jpg',        'question':'Botanical term?',     'answer':'basidiocarp',                   'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'bird.jpg',               'question':'Pollinator?',         'answer':'bird',                          'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'bee.jpg',                'question':'Pollinator?',         'answer':'bee',                           'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'wind.jpg',               'question':'Pollinator?',         'answer':'wind',                          'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'samara.jpg',             'question':'Fruit type?',         'answer':'samara',                        'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'aggregate-follicle.jpg', 'question':'Fruit type?',         'answer':'aggregate follicle',            'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'aggregate-drupe.jpg',    'question':'Fruit type?',         'answer':'aggregate drupe',               'attrcolor':'black', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'berry.jpg',              'question':'Fruit type?',         'answer':'berry',                         'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'scorpioid-cyme.jpg',     'question':'Inflorescence type?', 'answer':'scorpioid (or helicoid) cyme',  'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'raceme.jpg',             'question':'Inflorescence type?', 'answer':'raceme',                        'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'umbel.jpg',              'question':'Inflorescence type?', 'answer':'umbel',                         'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'compound-umbel.jpg',     'question':'Inflorescence type?', 'answer':'compound umbel',                'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'cyme.jpg',               'question':'Inflorescence type?', 'answer':'cyme',                          'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'solitary.jpg',           'question':'Inflorescence type?', 'answer':'solitary',                      'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'head.jpg',               'question':'Inflorescence type?', 'answer':'head',                          'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'spike.jpg',              'question':'Inflorescence type?', 'answer':'spike',                         'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'spike2.jpg',             'question':'Inflorescence type?', 'answer':'spike',                         'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' },
    {'filename':'catkin.jpg',             'question':'Inflorescence type?', 'answer':'catkin',                        'attrcolor':'white', 'attribution':'Photo by Paul O. Lewis' }
];
